[tool.uv.sources]
irisml-tasks-training = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
item-matching = [{ index = "pytorch-cpu", marker = "platform_system == 'Linux'" }, { index = "pytorch-cpu", marker = "platform_system == 'Linux'" }]
