services:
  - type: web
    name: faceswap-app
    runtime: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
    disk:
      name: uploads
      mountPath: /opt/render/project/src
      sizeGB: 1 