services:
  - type: web
    name: faceswap-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      which gunicorn
      pip show gunicorn
      npm install
      npx webpack --mode production
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: DATABASE_URL
        value: sqlite:///local.db
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 